#!/usr/bin/env python3
"""Capture exact DSV4 HTTP wire traffic and keep full native logging enabled.

The host process starts a tiny AF_PACKET recorder inside the running DSV4
container's network namespace.  It writes standard Ethernet PCAP files and
rotates only at packet boundaries.  In parallel it periodically re-enables
SGLang level-3 JSON request logging, covering container restarts or runtime
logging changes without restarting the model.
"""

from __future__ import annotations

import argparse
import contextlib
import datetime as dt
import inspect
import json
import os
import pathlib
import select
import signal
import struct
import subprocess
import time
import urllib.error
import urllib.request
from typing import Any, BinaryIO


PCAP_HEADER_SIZE = 24
PCAP_RECORD_HEADER_SIZE = 16
DEFAULT_ROTATE_BYTES = 2 * 1024**3
DEFAULT_SOCKET_BUFFER_BYTES = 4 * 1024**2
DEFAULT_CAPTURE_BATCH_BYTES = 1024**2

def packet_matches_http(packet: bytes, endpoint_ips: set[bytes], port: int) -> bool:
    """Match the configured IPv4 HTTP endpoint in an Ethernet/raw-lo frame."""
    if len(packet) < 34:
        return False
    ether_type = struct.unpack("!H", packet[12:14])[0]
    ip_offset = 14
    if ether_type == 0x8100 and len(packet) >= 38:
        ether_type = struct.unpack("!H", packet[16:18])[0]
        ip_offset = 18
    if ether_type != 0x0800 or len(packet) < ip_offset + 20:
        return False
    ihl = (packet[ip_offset] & 0x0F) * 4
    if ihl < 20 or packet[ip_offset + 9] != 6:
        return False
    tcp_offset = ip_offset + ihl
    if len(packet) < tcp_offset + 4:
        return False
    source_ip = packet[ip_offset + 12 : ip_offset + 16]
    destination_ip = packet[ip_offset + 16 : ip_offset + 20]
    source_port, destination_port = struct.unpack("!HH", packet[tcp_offset : tcp_offset + 4])
    return (source_ip in endpoint_ips and source_port == port) or (
        destination_ip in endpoint_ips and destination_port == port
    )


def kernel_http_filter(port: int) -> list[tuple[int, int, int, int]]:
    """Classic BPF: IPv4 TCP port, Ethernet or one VLAN tag.

    Generated by libpcap/tcpdump -ddd -y EN10MB -s 262144 with:
    'ip proto 6 and tcp port PORT or (vlan and ip proto 6 and tcp port PORT)'.
    Filter before the receive queue: all-interface capture also sees heavy
    NCCL/ZMQ traffic, which must not crowd HTTP out of that queue.
    """
    if not 1 <= port <= 65535:
        raise ValueError("Invalid TCP capture port")
    return [
        (40, 0, 0, 12), (21, 0, 9, 2048), (48, 0, 0, 23),
        (21, 0, 22, 6), (40, 0, 0, 20), (69, 20, 0, 8191),
        (177, 0, 0, 14), (72, 0, 0, 14), (21, 16, 0, port),
        (72, 0, 0, 16), (21, 14, 15, port), (21, 2, 0, 33024),
        (21, 1, 0, 34984), (21, 0, 12, 37120), (40, 0, 0, 16),
        (21, 0, 10, 2048), (48, 0, 0, 27), (21, 0, 8, 6),
        (40, 0, 0, 24), (69, 6, 0, 8191), (177, 0, 0, 18),
        (72, 0, 0, 18), (21, 2, 0, port), (72, 0, 0, 20),
        (21, 0, 1, port), (6, 0, 0, 262144), (6, 0, 0, 0),
    ]


def attach_kernel_http_filter(sock, port: int) -> None:
    import ctypes
    import socket

    class Instruction(ctypes.Structure):
        _fields_ = [("code", ctypes.c_ushort), ("jt", ctypes.c_ubyte),
                    ("jf", ctypes.c_ubyte), ("k", ctypes.c_uint32)]

    class Program(ctypes.Structure):
        _fields_ = [("length", ctypes.c_ushort),
                    ("instructions", ctypes.POINTER(Instruction))]

    bytecode = kernel_http_filter(port)
    instructions = (Instruction * len(bytecode))(*(Instruction(*i) for i in bytecode))
    program = Program(len(bytecode), instructions)
    # Linux SO_ATTACH_FILTER copies the pointed-to instructions synchronously.
    # Fail closed if attachment fails; do not silently run an unfiltered socket.
    sock.setsockopt(socket.SOL_SOCKET, 26, bytes(program))


CONTAINER_CAPTURE_PROGRAM = (
    inspect.getsource(packet_matches_http)
    + inspect.getsource(kernel_http_filter)
    + inspect.getsource(attach_kernel_http_filter)
) + r"""
import json
import os
import signal
import socket
import struct
import sys
import time

interface = sys.argv[1]
container_ip = socket.inet_aton(sys.argv[2])
endpoint_ips = {container_ip}
if interface in ("any", "lo"):
    endpoint_ips.add(socket.inet_aton("127.0.0.1"))
port = int(sys.argv[3])
pid_path = sys.argv[4]
requested_rcvbuf = int(sys.argv[5])
batch_bytes = int(sys.argv[6])
running = True
kernel_packets = 0
kernel_drops = 0
matched_packets = 0

SOL_PACKET = 263
PACKET_STATISTICS = 6

def stop(_signum, _frame):
    global running
    running = False

signal.signal(signal.SIGINT, stop)
signal.signal(signal.SIGTERM, stop)
with open(pid_path, "w", encoding="ascii") as handle:
    handle.write(str(os.getpid()))

sock = socket.socket(socket.AF_PACKET, socket.SOCK_RAW, socket.htons(3))
attach_kernel_http_filter(sock, port)
sock.setsockopt(socket.SOL_SOCKET, socket.SO_RCVBUF, requested_rcvbuf)
if interface != "any":
    sock.bind((interface, 0))
sock.settimeout(0.1)
actual_rcvbuf = sock.getsockopt(socket.SOL_SOCKET, socket.SO_RCVBUF)
output = sys.stdout.buffer
output.write(struct.pack("<IHHIIII", 0xA1B2C3D4, 2, 4, 0, 0, 262144, 1))
output.flush()
pending = bytearray()
last_output_flush = time.monotonic()
last_stats = time.monotonic()

def emit_status(event):
    global kernel_packets, kernel_drops
    try:
        raw = sock.getsockopt(SOL_PACKET, PACKET_STATISTICS, 12)
        packets, drops = struct.unpack_from("II", raw)
    except OSError:
        packets = drops = 0
    kernel_packets += packets
    kernel_drops += drops
    value = {
        "event": event,
        "actual_rcvbuf": actual_rcvbuf,
        "requested_rcvbuf": requested_rcvbuf,
        "batch_bytes": batch_bytes,
        "kernel_packets": kernel_packets,
        "kernel_drops": kernel_drops,
        "matched_packets": matched_packets,
        "kernel_filter": "ipv4_tcp_port",
    }
    sys.stderr.write(json.dumps(value, separators=(",", ":")) + "\n")
    sys.stderr.flush()

def flush_output():
    global last_output_flush
    if pending:
        output.write(pending)
        output.flush()
        pending.clear()
    last_output_flush = time.monotonic()

emit_status("capture_config")

try:
    while running:
        try:
            packet, address = sock.recvfrom(262144)
        except socket.timeout:
            now = time.monotonic()
            if pending and now - last_output_flush >= 0.1:
                flush_output()
            if now - last_stats >= 5.0:
                emit_status("packet_stats")
                last_stats = now
            continue
        # AF_PACKET observes both outgoing and incoming copies on loopback.
        # Retain one copy; keep both directions on ordinary Ethernet devices.
        if address[0] == "lo" and address[2] == socket.PACKET_OUTGOING:
            continue
        if not packet_matches_http(packet, endpoint_ips, port):
            continue
        timestamp = time.time()
        seconds = int(timestamp)
        microseconds = int((timestamp - seconds) * 1_000_000)
        pending.extend(struct.pack("<IIII", seconds, microseconds, len(packet), len(packet)))
        pending.extend(packet)
        matched_packets += 1
        now = time.monotonic()
        if len(pending) >= batch_bytes or now - last_output_flush >= 0.1:
            flush_output()
        if now - last_stats >= 5.0:
            emit_status("packet_stats")
            last_stats = now
finally:
    flush_output()
    emit_status("capture_final")
    sock.close()
    try:
        os.unlink(pid_path)
    except FileNotFoundError:
        pass
"""


def iso_utc() -> str:
    return dt.datetime.now(dt.timezone.utc).isoformat().replace("+00:00", "Z")


def atomic_json(path: pathlib.Path, value: Any) -> None:
    temporary = path.with_name(f".{path.name}.{os.getpid()}.tmp")
    temporary.write_text(json.dumps(value, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    temporary.chmod(0o600)
    os.replace(temporary, path)


def append_jsonl(path: pathlib.Path, value: Any) -> None:
    with path.open("a", encoding="utf-8") as handle:
        handle.write(json.dumps(value, ensure_ascii=False, sort_keys=True) + "\n")
        handle.flush()


def read_exact(stream: BinaryIO, size: int) -> bytes:
    chunks = []
    remaining = size
    while remaining:
        chunk = stream.read(remaining)
        if not chunk:
            return b"" if remaining == size else b"".join(chunks)
        chunks.append(chunk)
        remaining -= len(chunk)
    return b"".join(chunks)


def container_ip(container: str) -> str:
    command = [
        "docker",
        "inspect",
        "--format",
        "{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}",
        container,
    ]
    completed = subprocess.run(command, check=True, capture_output=True, text=True)
    value = completed.stdout.strip()
    if not value:
        raise RuntimeError(f"container {container!r} has no IPv4 address")
    return value


def enable_native_logging(base_url: str, api_key_file: pathlib.Path | None = None) -> tuple[bool, str]:
    payload = json.dumps({"log_requests": True, "log_requests_level": 3, "log_requests_format": "json"}).encode()
    headers = {"Content-Type": "application/json"}
    if api_key_file is not None:
        try:
            key = api_key_file.read_text(encoding="utf-8").strip()
        except OSError as error:
            return False, f"Unable to read capture API key ({type(error).__name__})"
        if not key or "\n" in key or "\r" in key:
            return False, "Capture API key must be a nonempty single line"
        headers["Authorization"] = "Bearer " + key
    request = urllib.request.Request(
        f"{base_url.rstrip('/')}/configure_logging",
        data=payload,
        headers=headers,
        method="POST",
    )
    try:
        with urllib.request.urlopen(request, timeout=10) as response:
            body = response.read(4_096).decode("utf-8", errors="replace")
            return response.status == 200, body
    except (OSError, urllib.error.URLError) as error:
        return False, repr(error)


def container_identity(container: str) -> dict[str, Any]:
    """Record deployment identity without dumping credential-bearing env/mounts."""
    template = ('{"id":{{json .Id}},"image_id":{{json .Image}},'
                '"image_tag":{{json .Config.Image}},"init_pid":{{.State.Pid}},'
                '"started_at":{{json .State.StartedAt}}}')
    result = subprocess.run(["docker", "inspect", "--format", template, container],
                            check=True, capture_output=True, text=True)
    return json.loads(result.stdout)


class WireCapture:
    def __init__(self, args: argparse.Namespace) -> None:
        self.args = args
        self.output_dir = args.output_dir.resolve()
        self.status_path = self.output_dir / "status.json"
        self.events_path = self.output_dir / "events.jsonl"
        self.stop_requested = False
        self.process: subprocess.Popen[bytes] | None = None
        self.stderr_handle: BinaryIO | None = None
        self.current_handle: BinaryIO | None = None
        self.current_bytes = 0
        self.current_index = -1
        self.global_header = b""
        self.packet_count = 0
        self.capture_bytes = 0
        self.native_logging_refreshes = 0
        self.native_logging_errors = 0
        self.capture_kernel_packets = 0
        self.capture_kernel_drops = 0
        self.capture_matched_packets = 0
        self.capture_socket_buffer_bytes = 0
        self._reported_kernel_drops = 0
        self.started = dt.datetime.now(dt.timezone.utc)
        self.deadline = time.monotonic() + args.duration_seconds
        self.container_ip = ""
        self.pid_path = f"/tmp/dsv4-wire-{os.getpid()}.pid"

    def setup(self) -> None:
        self.output_dir.mkdir(parents=True, exist_ok=False)
        self.output_dir.chmod(0o700)
        self.container_ip = container_ip(self.args.container)
        expected_end = self.started + dt.timedelta(seconds=self.args.duration_seconds)
        atomic_json(
            self.output_dir / "config.json",
            {
                "start_utc": self.started.isoformat().replace("+00:00", "Z"),
                "expected_end_utc": expected_end.isoformat().replace("+00:00", "Z"),
                "duration_seconds": self.args.duration_seconds,
                "container": self.args.container,
                "deployment": container_identity(self.args.container),
                "recorder_pid": os.getpid(),
                "wrapper_pid": os.getppid(),
                "container_ip": self.container_ip,
                "interface": self.args.interface,
                "includes_loopback": self.args.interface in ("any", "lo"),
                "kernel_filter": "ipv4_tcp_port",
                "authenticated_logging": self.args.api_key_file is not None,
                "port": self.args.port,
                "rotate_bytes": self.args.rotate_bytes,
                "socket_buffer_bytes_requested": self.args.socket_buffer_bytes,
                "capture_batch_bytes": self.args.capture_batch_bytes,
                "native_logging": "SGLang JSON level 3 refreshed periodically",
                "wire_capture": "Ethernet PCAP containing exact unencrypted HTTP traffic",
                "sensitivity": "Contains complete prompts, responses, and HTTP headers; directory mode is 0700",
            },
        )
        append_jsonl(self.events_path, {"at": iso_utc(), "event": "wire_capture_started"})

    def start_container_capture(self) -> None:
        command = [
            "docker",
            "exec",
            "-i",
            self.args.container,
            "python3",
            "-u",
            "-c",
            CONTAINER_CAPTURE_PROGRAM,
            self.args.interface,
            self.container_ip,
            str(self.args.port),
            self.pid_path,
            str(self.args.socket_buffer_bytes),
            str(self.args.capture_batch_bytes),
        ]
        self.stderr_handle = (self.output_dir / "wire-capture.stderr.log").open("wb")
        self.process = subprocess.Popen(
            command,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            # select() watches the OS pipe. BufferedReader can prefetch extra
            # PCAP records into Python and make the fd look idle even though
            # complete records are waiting in userspace, delaying live
            # analysis until shutdown. Keep both pipes unbuffered here; the
            # container recorder already batches stdout writes.
            bufsize=0,
        )
        if self.process.stdout is None:
            raise RuntimeError("docker exec did not expose capture stdout")
        self.global_header = read_exact(self.process.stdout, PCAP_HEADER_SIZE)
        if len(self.global_header) != PCAP_HEADER_SIZE:
            raise RuntimeError("wire recorder did not emit a complete PCAP header")
        self.open_next_file()

    def read_capture_telemetry(self) -> bool:
        if self.process is None or self.process.stderr is None:
            return False
        line = self.process.stderr.readline()
        if not line:
            return False
        if self.stderr_handle is not None:
            self.stderr_handle.write(line)
            self.stderr_handle.flush()
        try:
            value = json.loads(line)
        except (UnicodeDecodeError, json.JSONDecodeError):
            return True
        if not isinstance(value, dict):
            return True
        self.capture_kernel_packets = int(value.get("kernel_packets") or 0)
        self.capture_kernel_drops = int(value.get("kernel_drops") or 0)
        self.capture_matched_packets = int(value.get("matched_packets") or 0)
        self.capture_socket_buffer_bytes = int(value.get("actual_rcvbuf") or 0)
        if self.capture_kernel_drops > self._reported_kernel_drops:
            append_jsonl(
                self.events_path,
                {
                    "at": iso_utc(),
                    "event": "packet_capture_drop",
                    "new_drops": self.capture_kernel_drops - self._reported_kernel_drops,
                    "total_drops": self.capture_kernel_drops,
                    "actual_socket_buffer_bytes": self.capture_socket_buffer_bytes,
                },
            )
            self._reported_kernel_drops = self.capture_kernel_drops
        return True

    def drain_capture_telemetry(self) -> None:
        if self.process is None or self.process.stderr is None:
            return
        while True:
            ready, _, _ = select.select([self.process.stderr], [], [], 0)
            if not ready:
                break
            if not self.read_capture_telemetry():
                break

    def open_next_file(self) -> None:
        if self.current_handle is not None:
            self.current_handle.close()
        self.current_index += 1
        path = self.output_dir / f"traffic-{self.current_index:04d}.pcap"
        self.current_handle = path.open("wb")
        self.current_handle.write(self.global_header)
        self.current_handle.flush()
        path.chmod(0o600)
        self.current_bytes = len(self.global_header)
        append_jsonl(self.events_path, {"at": iso_utc(), "event": "pcap_opened", "path": path.name})

    def read_capture_record(self) -> bool:
        if self.process is None or self.process.stdout is None:
            raise RuntimeError("capture process unavailable")
        record_header = read_exact(self.process.stdout, PCAP_RECORD_HEADER_SIZE)
        if not record_header:
            return False
        if len(record_header) != PCAP_RECORD_HEADER_SIZE:
            raise RuntimeError("wire recorder returned a partial PCAP record header")
        _, _, captured_length, _ = struct.unpack("<IIII", record_header)
        packet = read_exact(self.process.stdout, captured_length)
        if len(packet) != captured_length:
            raise RuntimeError("wire recorder returned a partial packet")
        record_size = len(record_header) + len(packet)
        if self.current_bytes + record_size > self.args.rotate_bytes and self.current_bytes > PCAP_HEADER_SIZE:
            self.open_next_file()
        if self.current_handle is None:
            raise RuntimeError("PCAP output file is not open")
        self.current_handle.write(record_header)
        self.current_handle.write(packet)
        self.current_bytes += record_size
        self.capture_bytes += record_size
        self.packet_count += 1
        return True

    def status(self, state: str, **extra: Any) -> None:
        atomic_json(
            self.status_path,
            {
                "state": state,
                "pid": os.getpid(),
                "heartbeat_utc": iso_utc(),
                "remaining_seconds": round(max(0.0, self.deadline - time.monotonic()), 1),
                "container_ip": self.container_ip,
                "packets": self.packet_count,
                "capture_bytes": self.capture_bytes,
                "pcap_files": self.current_index + 1,
                "native_logging_refreshes": self.native_logging_refreshes,
                "native_logging_errors": self.native_logging_errors,
                "capture_kernel_packets": self.capture_kernel_packets,
                "capture_kernel_drops": self.capture_kernel_drops,
                "capture_matched_packets": self.capture_matched_packets,
                "capture_socket_buffer_bytes": self.capture_socket_buffer_bytes,
                **extra,
            },
        )

    def refresh_native_logging(self) -> None:
        success, detail = enable_native_logging(self.args.base_url, self.args.api_key_file)
        if success:
            self.native_logging_refreshes += 1
        else:
            self.native_logging_errors += 1
            append_jsonl(
                self.events_path,
                {"at": iso_utc(), "event": "native_logging_refresh_failed", "detail": detail},
            )

    def stop_container_capture(self) -> None:
        subprocess.run(
            [
                "docker",
                "exec",
                self.args.container,
                "python3",
                "-c",
                (
                    "import os,signal; "
                    f"p={self.pid_path!r}; "
                    "os.kill(int(open(p, encoding='ascii').read()), signal.SIGTERM) if os.path.exists(p) else None"
                ),
            ],
            check=False,
            capture_output=True,
            timeout=10,
        )
        if self.process is not None:
            drain_deadline = time.monotonic() + 5
            while self.process.poll() is None and time.monotonic() < drain_deadline:
                readers = []
                if self.process.stdout is not None:
                    readers.append(self.process.stdout)
                if self.process.stderr is not None:
                    readers.append(self.process.stderr)
                ready, _, _ = select.select(readers, [], [], 0.1)
                if self.process.stderr is not None and self.process.stderr in ready:
                    self.read_capture_telemetry()
                if self.process.stdout is not None and self.process.stdout in ready:
                    self.read_capture_record()
            if self.process.poll() is None:
                self.process.terminate()
                with contextlib.suppress(subprocess.TimeoutExpired):
                    self.process.wait(timeout=5)
            if self.process.poll() is None:
                self.process.kill()
                self.process.wait(timeout=5)
            if self.process.stdout is not None:
                while self.read_capture_record():
                    pass
            self.drain_capture_telemetry()
            if self.current_handle is not None:
                self.current_handle.flush()

    def run(self) -> int:
        self.setup()
        self.refresh_native_logging()
        self.start_container_capture()
        self.status("running")
        if self.process is None or self.process.stdout is None:
            raise RuntimeError("capture process unavailable")
        next_logging_refresh = time.monotonic() + self.args.logging_refresh_seconds
        next_status = time.monotonic() + 5
        while not self.stop_requested and time.monotonic() < self.deadline:
            if self.process.poll() is not None:
                raise RuntimeError(f"wire recorder exited with {self.process.returncode}")
            readers = [self.process.stdout]
            if self.process.stderr is not None:
                readers.append(self.process.stderr)
            ready, _, _ = select.select(readers, [], [], 1.0)
            now = time.monotonic()
            if self.process.stderr is not None and self.process.stderr in ready:
                self.read_capture_telemetry()
            if not ready:
                if now >= next_logging_refresh:
                    self.refresh_native_logging()
                    next_logging_refresh = now + self.args.logging_refresh_seconds
                if now >= next_status:
                    if self.current_handle is not None:
                        self.current_handle.flush()
                    self.status("running")
                    next_status = now + 5
                continue
            if self.process.stdout not in ready:
                continue
            if not self.read_capture_record():
                raise RuntimeError("wire recorder closed its capture stream")
            now = time.monotonic()
            if now >= next_logging_refresh:
                self.refresh_native_logging()
                next_logging_refresh = now + self.args.logging_refresh_seconds
            if now >= next_status:
                self.current_handle.flush()
                self.status("running")
                next_status = now + 5
        self.stop_container_capture()
        if self.current_handle is not None:
            self.current_handle.close()
            self.current_handle = None
        if self.stderr_handle is not None:
            self.stderr_handle.close()
            self.stderr_handle = None
        self.status("complete", stopped_early=self.stop_requested, actual_end_utc=iso_utc())
        append_jsonl(
            self.events_path,
            {"at": iso_utc(), "event": "wire_capture_finished", "packets": self.packet_count},
        )
        return 0


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=pathlib.Path, required=True)
    parser.add_argument("--duration-seconds", type=float, required=True)
    parser.add_argument("--container", default="dsv4")
    parser.add_argument("--interface", default="eth0", help="Network interface, or any to include container loopback")
    parser.add_argument("--port", type=int, default=8000)
    parser.add_argument("--base-url", default="http://127.0.0.1:8000")
    parser.add_argument("--api-key-file", type=pathlib.Path, help="Private local key file for authenticated logging configuration")
    parser.add_argument("--rotate-bytes", type=int, default=DEFAULT_ROTATE_BYTES)
    parser.add_argument(
        "--socket-buffer-bytes",
        type=int,
        default=DEFAULT_SOCKET_BUFFER_BYTES,
        help="Requested AF_PACKET receive buffer (Linux reports twice this size)",
    )
    parser.add_argument(
        "--capture-batch-bytes",
        type=int,
        default=DEFAULT_CAPTURE_BATCH_BYTES,
        help="Maximum PCAP bytes buffered before writing to the docker-exec pipe",
    )
    parser.add_argument("--logging-refresh-seconds", type=float, default=60)
    args = parser.parse_args()
    if (
        args.duration_seconds <= 0
        or args.rotate_bytes <= PCAP_HEADER_SIZE
        or args.socket_buffer_bytes <= 0
        or args.capture_batch_bytes <= 0
    ):
        parser.error("duration, rotate size, socket buffer, and batch size must be positive")
    if not 1 <= args.port <= 65535:
        parser.error("port must be between 1 and 65535")
    return args


def main() -> int:
    os.umask(0o077)
    capture = WireCapture(parse_args())

    def stop(_signum: int, _frame: Any) -> None:
        capture.stop_requested = True

    signal.signal(signal.SIGINT, stop)
    signal.signal(signal.SIGTERM, stop)
    try:
        return capture.run()
    except Exception as error:
        with contextlib.suppress(Exception):
            capture.stop_container_capture()
        if capture.output_dir.exists():
            with contextlib.suppress(Exception):
                capture.status("failed", fatal_error=repr(error))
                append_jsonl(
                    capture.events_path, {"at": iso_utc(), "event": "wire_capture_failed", "error": repr(error)}
                )
        raise


if __name__ == "__main__":
    raise SystemExit(main())
